language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
    - py.test --junit-xml=test_result.xml coveralls --cov=foo --cov-report=xml
after_success:
  - coveralls
